changelog:
  exclude:
    authors:
      - renovate[bot]
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
        - major
    - title: Features 🎉
      labels:
        - enhancement
        - feat
        - feature
        - minor
    - title: Other Changes
      labels:
        - "*"
