changelog:
  exclude:
    authors:
      - renovate[bot]
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
        - major
    - title: Features 🎉
      labels:
        - Semver-Minor
        - enhancement
        - feat
        - feature
    - title: Other Changes
      labels:
        - "*"
