name: Build Container Image

on:
  pull_request:
    branches:
      - main
      - alpha
    types:
      - closed
  workflow_dispatch:

jobs:
  call-workflow:
    uses: justsomescripts/common-actions/.github/workflows/container.build.yml@main
    secrets: inherit
    with:
      containerfile: Containerfile
    permissions: write-all
