name: Build Container Image

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build-container:
    uses: justsomescripts/common-actions/.github/workflows/container.build.yml@main
    secrets: inherit
    with:
      containerfile: Containerfile
    permissions:
      checks: write
      contents: write
