name: Check code

on:
  pull_request:
    branches:
      - release
    types:
      - opened
  workflow_dispatch:

permissions: write-all

jobs:
  call-workflow:
    uses: justsomescripts/common-actions/.github/workflows/container-build.yml@release
    secrets: inherit
    with:
      check_only: true