name: Check code

on:
  pull_request:
    branches:
      - main
    types:
      - opened

permissions: write-all

jobs:
  call-workflow:
    uses: justsomescripts/common-actions/.github/workflows/container-build.yml@main
    secrets: inherit
    with:
      check_only: true
