name: Build Container Image

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:

jobs:
  build-container:
    uses: justsomescripts/github-common-actions/.github/workflows/container.build.yml@main
    secrets: inherit
    with:
      containerfile: Containerfile
      sign_images: false
    permissions:
      checks: write
      contents: write
      packages: write
      security-events: write
